// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: mailing/mailing.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MailingNotificationServiceClient is the client API for MailingNotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MailingNotificationServiceClient interface {
	SendMail(ctx context.Context, in *MailSendTwoFactorAuthOtpPayload, opts ...grpc.CallOption) (*OkResponse, error)
}

type mailingNotificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMailingNotificationServiceClient(cc grpc.ClientConnInterface) MailingNotificationServiceClient {
	return &mailingNotificationServiceClient{cc}
}

func (c *mailingNotificationServiceClient) SendMail(ctx context.Context, in *MailSendTwoFactorAuthOtpPayload, opts ...grpc.CallOption) (*OkResponse, error) {
	out := new(OkResponse)
	err := c.cc.Invoke(ctx, "/mailing_notification_service.MailingNotificationService/SendMail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailingNotificationServiceServer is the server API for MailingNotificationService service.
// All implementations must embed UnimplementedMailingNotificationServiceServer
// for forward compatibility
type MailingNotificationServiceServer interface {
	SendMail(context.Context, *MailSendTwoFactorAuthOtpPayload) (*OkResponse, error)
	mustEmbedUnimplementedMailingNotificationServiceServer()
}

// UnimplementedMailingNotificationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMailingNotificationServiceServer struct {
}

func (UnimplementedMailingNotificationServiceServer) SendMail(context.Context, *MailSendTwoFactorAuthOtpPayload) (*OkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMail not implemented")
}
func (UnimplementedMailingNotificationServiceServer) mustEmbedUnimplementedMailingNotificationServiceServer() {
}

// UnsafeMailingNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MailingNotificationServiceServer will
// result in compilation errors.
type UnsafeMailingNotificationServiceServer interface {
	mustEmbedUnimplementedMailingNotificationServiceServer()
}

func RegisterMailingNotificationServiceServer(s grpc.ServiceRegistrar, srv MailingNotificationServiceServer) {
	s.RegisterService(&MailingNotificationService_ServiceDesc, srv)
}

func _MailingNotificationService_SendMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MailSendTwoFactorAuthOtpPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailingNotificationServiceServer).SendMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mailing_notification_service.MailingNotificationService/SendMail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailingNotificationServiceServer).SendMail(ctx, req.(*MailSendTwoFactorAuthOtpPayload))
	}
	return interceptor(ctx, in, info, handler)
}

// MailingNotificationService_ServiceDesc is the grpc.ServiceDesc for MailingNotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MailingNotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mailing_notification_service.MailingNotificationService",
	HandlerType: (*MailingNotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMail",
			Handler:    _MailingNotificationService_SendMail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mailing/mailing.proto",
}
